//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroFramework.Project.Service_TMS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service_TMS.ITMS")]
    public interface ITMS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS/Login", ReplyAction="http://tempuri.org/ITMS/LoginResponse")]
        bool Login(string userName, string passWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITMS/Login", ReplyAction="http://tempuri.org/ITMS/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string userName, string passWord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITMSChannel : MetroFramework.Project.Service_TMS.ITMS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TMSClient : System.ServiceModel.ClientBase<MetroFramework.Project.Service_TMS.ITMS>, MetroFramework.Project.Service_TMS.ITMS {
        
        public TMSClient() {
        }
        
        public TMSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TMSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TMSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string userName, string passWord) {
            return base.Channel.Login(userName, passWord);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string userName, string passWord) {
            return base.Channel.LoginAsync(userName, passWord);
        }
    }
}
